In [171]:
#problem Statement-- Develop an income classifier for indivisuals.

# import all necessary libraries  
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

#from sklearn.feature_extraction.text import tfidfvectorizer

In [172]:
data1 = pd.read_csv("income.csv")

In [173]:
data = data1.copy() #make a seperate copy so that origional data wont be touched 

In [174]:
data.head(9)

age       JobType         EdType        maritalstatus          occupation  \
0   45       Private        HS-grad             Divorced        Adm-clerical   
1   24   Federal-gov        HS-grad        Never-married        Armed-Forces   
2   44       Private   Some-college   Married-civ-spouse      Prof-specialty   
3   27       Private            9th        Never-married        Craft-repair   
4   20       Private   Some-college        Never-married               Sales   
5   44       Private        HS-grad              Widowed     Exec-managerial   
6   51       Private        HS-grad   Married-civ-spouse        Craft-repair   
7   20       Private        HS-grad   Married-civ-spouse   Machine-op-inspct   
8   17             ?           11th        Never-married                   ?   

      relationship                 race   gender  capitalgain  capitalloss  \
0    Not-in-family                White   Female            0            0   
1        Own-child                White     Male            0            0   
2          Husband                White     Male            0            0   
3   Other-relative                White     Male            0            0   
4    Not-in-family                White     Male            0            0   
5        Unmarried                Black   Female            0            0   
6          Husband   Amer-Indian-Eskimo     Male            0            0   
7          Husband                White     Male            0            0   
8        Own-child                White   Female            0            0   

   hoursperweek   nativecountry                        SalStat  
0            28   United-States   less than or equal to 50,000  
1            40   United-States   less than or equal to 50,000  
2            40   United-States            greater than 50,000  
3            40          Mexico   less than or equal to 50,000  
4            35   United-States   less than or equal to 50,000  
5            40   United-States   less than or equal to 50,000  
6            40   United-States   less than or equal to 50,000  
7            40   United-States   less than or equal to 50,000  
8             5   United-States   less than or equal to 50,000

In [175]:
data.info()
#to know data type and nameof column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31978 entries, 0 to 31977
Data columns (total 13 columns):
age              31978 non-null int64
JobType          31978 non-null object
EdType           31978 non-null object
maritalstatus    31978 non-null object
occupation       31978 non-null object
relationship     31978 non-null object
race             31978 non-null object
gender           31978 non-null object
capitalgain      31978 non-null int64
capitalloss      31978 non-null int64
hoursperweek     31978 non-null int64
nativecountry    31978 non-null object
SalStat          31978 non-null object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB


In [176]:
data.describe()
#summary of variables

age   capitalgain   capitalloss  hoursperweek
count  31978.000000  31978.000000  31978.000000  31978.000000
mean      38.579023   1064.360623     86.739352     40.417850
std       13.662085   7298.596271    401.594301     12.345285
min       17.000000      0.000000      0.000000      1.000000
25%       28.000000      0.000000      0.000000     40.000000
50%       37.000000      0.000000      0.000000     40.000000
75%       48.000000      0.000000      0.000000     45.000000
max       90.000000  99999.000000   4356.000000     99.000000

In [177]:
data.isna().sum()
#to check for any missing or null value.

age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64

In [178]:
data["JobType"].value_counts()
#question mart exist

 Private             22286
 Self-emp-not-inc     2499
 Local-gov            2067
 ?                    1809
 State-gov            1279
 Self-emp-inc         1074
 Federal-gov           943
 Without-pay            14
 Never-worked            7
Name: JobType, dtype: int64

In [179]:
data["occupation"].value_counts()
#question mark exist, it can be treated as missing data

 Prof-specialty       4038
 Craft-repair         4030
 Exec-managerial      3992
 Adm-clerical         3721
 Sales                3584
 Other-service        3212
 Machine-op-inspct    1966
 ?                    1816
 Transport-moving     1572
 Handlers-cleaners    1350
 Farming-fishing       989
 Tech-support          912
 Protective-serv       644
 Priv-house-serv       143
 Armed-Forces            9
Name: occupation, dtype: int64

In [180]:
data = pd.read_csv("income.csv", na_values=[" ?"])
#consider special symbol as NaN value

In [184]:
data.head(9)
#you can check at 8th position ? is replaced with NaN value. 

age       JobType         EdType        maritalstatus          occupation  \
0   45       Private        HS-grad             Divorced        Adm-clerical   
1   24   Federal-gov        HS-grad        Never-married        Armed-Forces   
2   44       Private   Some-college   Married-civ-spouse      Prof-specialty   
3   27       Private            9th        Never-married        Craft-repair   
4   20       Private   Some-college        Never-married               Sales   
5   44       Private        HS-grad              Widowed     Exec-managerial   
6   51       Private        HS-grad   Married-civ-spouse        Craft-repair   
7   20       Private        HS-grad   Married-civ-spouse   Machine-op-inspct   
8   17           NaN           11th        Never-married                 NaN   

      relationship                 race   gender  capitalgain  capitalloss  \
0    Not-in-family                White   Female            0            0   
1        Own-child                White     Male            0            0   
2          Husband                White     Male            0            0   
3   Other-relative                White     Male            0            0   
4    Not-in-family                White     Male            0            0   
5        Unmarried                Black   Female            0            0   
6          Husband   Amer-Indian-Eskimo     Male            0            0   
7          Husband                White     Male            0            0   
8        Own-child                White   Female            0            0   

   hoursperweek   nativecountry                        SalStat  
0            28   United-States   less than or equal to 50,000  
1            40   United-States   less than or equal to 50,000  
2            40   United-States            greater than 50,000  
3            40          Mexico   less than or equal to 50,000  
4            35   United-States   less than or equal to 50,000  
5            40   United-States   less than or equal to 50,000  
6            40   United-States   less than or equal to 50,000  
7            40   United-States   less than or equal to 50,000  
8             5   United-States   less than or equal to 50,000

In [185]:
data.isnull().sum()

#some NaN values are present in JobType and occupation input features. 

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [187]:
data2 = data.dropna()
#drop using dropna()method.

In [188]:
data2.isna().sum()
#now no any missng value. 

age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64

In [189]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 31977
Data columns (total 13 columns):
age              30162 non-null int64
JobType          30162 non-null object
EdType           30162 non-null object
maritalstatus    30162 non-null object
occupation       30162 non-null object
relationship     30162 non-null object
race             30162 non-null object
gender           30162 non-null object
capitalgain      30162 non-null int64
capitalloss      30162 non-null int64
hoursperweek     30162 non-null int64
nativecountry    30162 non-null object
SalStat          30162 non-null object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB


In [190]:
#to find correlation
corr = data.corr()
print(corr)

                   age  capitalgain  capitalloss  hoursperweek
age           1.000000     0.077490     0.057282      0.068299
capitalgain   0.077490     1.000000    -0.031499      0.079112
capitalloss   0.057282    -0.031499     1.000000      0.053106
hoursperweek  0.068299     0.079112     0.053106      1.000000


In [191]:
#our output variable is SalStat
data["SalStat"].value_counts()

 less than or equal to 50,000    24283
 greater than 50,000              7695
Name: SalStat, dtype: int64

In [192]:
data["SalStat"]= data["SalStat"].map({" less than or equal to 50,000":0, " greater than 50,000":1})
print(data["SalStat"]) 

#Machine Learning algorithm can not work with categorial variables, we can map with 0 and 1 using dictionary.

0        0
1        0
2        1
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       1
12       1
13       1
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       1
28       1
29       0
        ..
31948    0
31949    0
31950    1
31951    0
31952    1
31953    0
31954    0
31955    0
31956    0
31957    0
31958    0
31959    1
31960    0
31961    0
31962    0
31963    0
31964    0
31965    1
31966    0
31967    0
31968    0
31969    0
31970    1
31971    0
31972    1
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 31978, dtype: int64


In [193]:
new_data = pd.get_dummies(data, drop_first=True )
#convert it into numerical variables.

In [195]:
print(new_data.head(9))

   age  capitalgain  capitalloss  hoursperweek  SalStat  JobType_ Local-gov  \
0   45            0            0            28        0                   0   
1   24            0            0            40        0                   0   
2   44            0            0            40        1                   0   
3   27            0            0            40        0                   0   
4   20            0            0            35        0                   0   
5   44            0            0            40        0                   0   
6   51            0            0            40        0                   0   
7   20            0            0            40        0                   0   
8   17            0            0             5        0                   0   

   JobType_ Never-worked  JobType_ Private  JobType_ Self-emp-inc  \
0                      0                 1                      0   
1                      0                 0                      0   
2 

In [202]:
columns_list = list(new_data.columns)
print(columns_list)
len(columns_list)
#all the columns 

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Never-worked', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 

96

In [201]:
features = list(set(columns_list)-set(["SalStat"]))
print(features)
len(features)

#remove output variable

['nativecountry_ United-States', 'JobType_ Without-pay', 'occupation_ Armed-Forces', 'gender_ Male', 'nativecountry_ South', 'EdType_ Bachelors', 'JobType_ Self-emp-not-inc', 'race_ White', 'occupation_ Other-service', 'nativecountry_ England', 'nativecountry_ Philippines', 'occupation_ Prof-specialty', 'EdType_ 5th-6th', 'nativecountry_ Yugoslavia', 'EdType_ 7th-8th', 'capitalloss', 'nativecountry_ Haiti', 'relationship_ Other-relative', 'nativecountry_ Ireland', 'JobType_ Never-worked', 'nativecountry_ Columbia', 'nativecountry_ Canada', 'JobType_ Self-emp-inc', 'occupation_ Tech-support', 'race_ Black', 'nativecountry_ Taiwan', 'nativecountry_ Italy', 'occupation_ Transport-moving', 'nativecountry_ Outlying-US(Guam-USVI-etc)', 'nativecountry_ Portugal', 'EdType_ Doctorate', 'EdType_ Assoc-acdm', 'EdType_ 1st-4th', 'nativecountry_ Trinadad&Tobago', 'occupation_ Sales', 'maritalstatus_ Married-civ-spouse', 'occupation_ Exec-managerial', 'occupation_ Handlers-cleaners', 'capitalgain', 

95

In [204]:
x = new_data[features].values
print(x)

#prepare x variable with all the features.

[[1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 1]
 ...
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 1]
 [1 0 0 ... 0 0 0]]


In [207]:
y = new_data["SalStat"].values
print(y)

#our output variable

[0 0 1 ... 0 0 0]


In [208]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.3,random_state=0)
print(train_x.shape)

#split into training data set and testing dataset.

(22384, 95)


In [211]:
print(test_x.shape)

(9594, 95)


In [212]:
print(train_y.shape)

(22384,)


In [213]:
print(test_y.shape)

(9594,)


In [214]:
#create the instance of algorithm

logistic = LogisticRegression()

In [215]:
logistic.fit(train_x,train_y) 
#fit the model using fit()method 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [216]:
prediction = logistic.predict(test_x)

#predict the model on test x variable.

In [217]:
print(prediction)

[0 0 0 ... 0 0 0]


In [221]:
acc_score = accuracy_score(test_y,prediction)
#accuracy measurement

In [222]:
print(acc_score)

0.8518865957890348


In [223]:
con_mat = confusion_matrix(test_y,prediction)

In [224]:
print(con_mat)
#actual values VS Predicted values

[[6835  501]
 [ 920 1338]]


In [225]:
print("Misclassified Samples: %d" % (test_y != prediction).sum())

#we have 1421 misclassified values.

Misclassified Samples: 1421


# KNN Algorithm

In [227]:
from sklearn.neighbors import KNeighborsClassifier

In [229]:
knn = KNeighborsClassifier(n_neighbors=2)

In [230]:
knn.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [231]:
knn_predict = knn.predict(test_x)

In [232]:
print(knn_predict)

[0 0 0 ... 0 0 0]


In [233]:
acc_score = accuracy_score(test_y,knn_predict)

In [234]:
print(acc_score)

0.8431311236189285


In [235]:
print("Missclassified Samples:%d" %(test_y!=knn_predict).sum())

Missclassified Samples:1505


In [236]:
con_mat = confusion_matrix(test_y,knn_predict)

In [237]:
print(con_mat)

[[6995  341]
 [1164 1094]]


In [ ]:
#if we use Logistic Regression algorithm accuracy is high as compare to KNN algorithm.
#so Logistic Regression algorithm bests fits here with high accuracy.